# this file is meant for the expect-lite tool
# see: http://expect-lite.sourceforge.net/
# not to be called directly, included by php.elt and pascal.elt
# to test functional equivalence between Pascal and PHP code
>w
<<Do you want results stored in printable diskfile? (Y/N)
>n
<<Your CHORD (format something like: d4-g#4-c#5, or f4db4bb3ab4,
<<   each note name to be ended by its octave position digit (a440 = a4))
>d4-g#4-c#5-f4db4bb3ab4-c1-c#2-e3
<<c1<41> c#2<39> e3<44> a#3<27> c#4<32> d4<90> f4<35> g#4<21> c#5<11> 
<<TOTAL--><170>; DSG is 37 (class: IV); Hindemith Root: c#2
<<Do you wish to change this chord by hand? (Y/N)
>y
<<Type pitches to be added (if any)
> 
<<Type pitches to be deleted (if any)
>c#2
<<c1<20> e3<42> a#3<25> c#4<52> d4<77> f4<34> g#4<21> c#5<21> 
<<TOTAL--><146>; DSG is 36 (class: IV); Hindemith Root: a#3
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>t
<<Enter the target DSG:
>100
<<b0<12> d3<72> c4<71> c#4<116> d4<71> d#4<105> e4<82> d#5<40> 
<<TOTAL--><284>; DSG is 71 (class: V); Hindemith Root: e4
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>d
<<a#0<4> d3<30> c4<35> d4<29> d#4<79> d5<11> 
<<TOTAL--><94>; DSG is 31 (class: IV); Hindemith Root: d#4
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>i
<<b0<9> d#3<38> c4<35> d4<68> d#4<36> d5<26> 
<<TOTAL--><106>; DSG is 35 (class: IV); Hindemith Root: b0
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>i
<<c1<14> e3<38> c#4<79> d4<79> d#4<89> d5<30> 
<<TOTAL--><164>; DSG is 54 (class: IV); Hindemith Root: c1
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>t
<<Enter the target DSG:
>5
<<b0<5> d3<4> a3<10> d4<3> f4<12> d5<1> 
<<TOTAL--><17>; DSG is 5 (class: II); Hindemith Root: d3
<<Do you wish to change this chord by hand? (Y/N)
>y
<<Type pitches to be added (if any)
>f#4
<<Type pitches to be deleted (if any)
> 
<<b0<5> d3<6> a3<13> d4<5> f4<46> f#4<45> d5<2> 
<<TOTAL--><61>; DSG is 17 (class: III); Hindemith Root: b0
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>t
<<Enter the target DSG:
>60
<<c#1<17> d3<40> g3<38> e4<79> f4<86> f#4<73> d#5<49> 
<<TOTAL--><191>; DSG is 54 (class: IV); Hindemith Root: g3
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>i
<<d1<18> d#3<60> g3<37> e4<74> f4<105> f#4<78> e5<28> 
<<TOTAL--><200>; DSG is 57 (class: V); Hindemith Root: g3
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>i
<<c#1<7> d#3<52> g3<39> e4<71> f4<105> f#4<78> e5<27> 
<<TOTAL--><189>; DSG is 54 (class: IV); Hindemith Root: f#4
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>d
<<c1<4> d#3<40> f#3<18> e4<42> f#4<14> e5<16> 
<<TOTAL--><67>; DSG is 22 (class: IV); Hindemith Root: c1
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>d
<<b0<1> d#3<6> f#3<8> d#4<4> f#4<5> d#5<1> 
<<TOTAL--><12>; DSG is 4 (class: II); Hindemith Root: b0
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>t
<<Enter the target DSG:
>0
<<b0<1> d#3<6> f#3<8> d#4<4> f#4<5> d#5<1> 
<<TOTAL--><12>; DSG is 4 (class: II); Hindemith Root: b0
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>w
<<Aiming for a target dissonance, or using parallel subset motion? (T/P)
>p
<<Increasing, or diminishing the dissonance? (I/D)
>i
<<c1<3> e3<37> f#3<44> d#4<48> g4<29> e5<18> 
<<TOTAL--><89>; DSG is 29 (class: IV); Hindemith Root: c1
<<Do you wish to change this chord by hand? (Y/N)
>n
<<Shall I work on it, or abandon it? (W/A)
>a
<<Do you want to leave the program? (Y/N)
>y
